# Generated by Django 3.0.5 on 2023-02-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=34, null=True)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=14)),
                ('message', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterHackathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Poster_Img', models.ImageField(upload_to='images/')),
                ('type_of_hack', models.CharField(max_length=20)),
                ('title_hack', models.CharField(max_length=20)),
                ('Organization_name', models.CharField(max_length=20)),
                ('Desc_hack', models.TextField(max_length=200)),
                ('rules', models.TextField(max_length=200)),
                ('hack_url', models.CharField(max_length=200)),
                ('festival_name', models.CharField(max_length=20)),
                ('mode_of_event', models.CharField(max_length=200)),
                ('cat_of_hack', models.CharField(max_length=200)),
                ('Guidelines', models.TextField(max_length=500)),
                ('start_date_time', models.DateField(max_length=100)),
                ('end_date_time', models.DateField(max_length=100)),
                ('minimum_no_team', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
