# Generated by Django 3.0.5 on 2023-02-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230217_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerhackathon',
            old_name='Desc_hack',
            new_name='Description_hack',
        ),
        migrations.RenameField(
            model_name='registerhackathon',
            old_name='cat_of_hack',
            new_name='category_of_hackathon',
        ),
        migrations.RenameField(
            model_name='registerhackathon',
            old_name='hack_url',
            new_name='hackathon_url',
        ),
        migrations.RenameField(
            model_name='registerhackathon',
            old_name='title_hack',
            new_name='title_hackathon',
        ),
        migrations.RenameField(
            model_name='registerhackathon',
            old_name='type_of_hack',
            new_name='type_of_hackathon',
        ),
        migrations.AddField(
            model_name='registerhackathon',
            name='maximum_no_team',
            field=models.IntegerField(default=0),
        ),
    ]
