# Generated by Django 3.0.5 on 2023-02-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230217_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerhackathon',
            name='mode_of_event',
            field=models.BooleanField(),
        ),
    ]
