# Generated by Django 3.0.5 on 2023-02-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_registerhackathon_my_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerhackathon',
            name='my_field',
            field=models.CharField(choices=[('0', 'Online'), ('1', 'Offline')], default='a', max_length=1),
        ),
    ]
