# Generated by Django 3.0.5 on 2023-02-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230217_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerhackathon',
            name='my_field',
        ),
        migrations.AlterField(
            model_name='registerhackathon',
            name='mode_of_event',
            field=models.CharField(choices=[('0', 'Online'), ('1', 'Offline')], default='a', max_length=1),
        ),
    ]
