# Generated by Django 3.0.5 on 2023-02-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230217_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipateHackathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
