# Generated by Django 3.0.5 on 2023-02-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_participatehackathon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerhackathon',
            old_name='title_hackathon',
            new_name='name_hackathon',
        ),
    ]
