# Generated by Django 3.0.5 on 2023-02-17 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20230217_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerhackathon',
            name='Poster_Img',
        ),
        migrations.RemoveField(
            model_name='registerhackathon',
            name='category_of_hackathon',
        ),
        migrations.RemoveField(
            model_name='registerhackathon',
            name='type_of_hackathon',
        ),
    ]
