# Generated by Django 3.0.5 on 2023-02-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20230217_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerhackathon',
            name='festival_name',
        ),
        migrations.AlterField(
            model_name='registerhackathon',
            name='end_date_time',
            field=models.DateTimeField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registerhackathon',
            name='start_date_time',
            field=models.DateTimeField(max_length=100),
        ),
    ]
