# Generated by Django 3.0.5 on 2023-02-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20230217_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
