# Generated by Django 3.0.5 on 2023-02-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20230217_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('emailid', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('mobileno', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=100)),
                ('password1', models.CharField(max_length=100)),
                ('collegename', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='registerhackathon',
            name='mode_of_event',
            field=models.CharField(choices=[('Online', '0'), ('Offline', '1')], default='Offline', max_length=10),
        ),
    ]
