# Generated by Django 3.0.5 on 2023-02-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20230217_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='participatehackathon',
            name='c_spec',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='participatehackathon',
            name='citizen',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='participatehackathon',
            name='college_name',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='participatehackathon',
            name='course',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='participatehackathon',
            name='diff_able',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='participatehackathon',
            name='domain',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='participatehackathon',
            name='email',
            field=models.EmailField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='participatehackathon',
            name='gender',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='participatehackathon',
            name='name',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='participatehackathon',
            name='year',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
