# Generated by Django 3.0.5 on 2023-02-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20230217_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='participatehackathon',
            name='resume',
            field=models.FileField(default=0, upload_to='documents/'),
        ),
    ]
