# Generated by Django 3.0.5 on 2023-02-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_participatehackathon_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participatehackathon',
            name='email',
            field=models.EmailField(default=0, max_length=200),
        ),
    ]
