# Generated by Django 3.0.5 on 2023-02-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20230217_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participatehackathon',
            name='resume',
            field=models.FileField(default=0, upload_to='media/documents/'),
        ),
    ]
