# Generated by Django 3.0.5 on 2023-02-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_participatehackathon_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='participatehackathon',
            name='hack_id',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='registerhackathon',
            name='domain',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='registerhackathon',
            name='skills',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='participatehackathon',
            name='no_of_repos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participatehackathon',
            name='no_of_stars',
            field=models.IntegerField(default=0),
        ),
    ]
