# Generated by Django 3.0.5 on 2023-02-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20230218_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='participatehackathon',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
