# Generated by Django 3.0.5 on 2023-02-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='participatehackathon',
            name='teamname',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
